import { getInitialSettings } from '../utils/settings/settings.js'
import sample from 'lodash-es/sample.js'

/**
 * Codex-style status labels (Thinking / Waiting / Running tools) are the default.
 * Set TOVYR_ACCURATE_SPINNER=0 to restore silly random verbs (Schlepping, …).
 */
export function isTovyrAccurateSpinnerEnabled(): boolean {
  if (process.env.TOVYR_ACCURATE_SPINNER === '0') return false
  if (process.env.TOVYR_ACCURATE_SPINNER === '1') return true
  return true
}

export function getSpinnerVerbs(): string[] {
  const settings = getInitialSettings()
  const config = settings.spinnerVerbs
  if (!config) {
    return SPINNER_VERBS
  }
  if (config.mode === 'replace') {
    return config.verbs.length > 0 ? config.verbs : SPINNER_VERBS
  }
  return [...SPINNER_VERBS, ...config.verbs]
}

/** Random loading label from SPINNER_VERBS (settings-aware). */
export function pickSpinnerVerb(): string {
  return sample(getSpinnerVerbs()) ?? 'Working'
}

// Spinner verbs for loading messages
export const SPINNER_VERBS = [
  'Accomplishing',
  'Actioning',
  'Actualizing',
  'Architecting',
  'Baking',
  'Beaming',
  "Beboppin'",
  'Befuddling',
  'Billowing',
  'Blanching',
  'Bloviating',
  'Boogieing',
  'Boondoggling',
  'Booping',
  'Bootstrapping',
  'Brewing',
  'Bunning',
  'Burrowing',
  'Calculating',
  'Canoodling',
  'Caramelizing',
  'Cascading',
  'Catapulting',
  'Cerebrating',
  'Channeling',
  'Channelling',
  'Choreographing',
  'Churning',
  'Coalescing',
  'Cogitating',
  'Combobulating',
  'Composing',
  'Computing',
  'Concocting',
  'Considering',
  'Contemplating',
  'Cooking',
  'Crafting',
  'Creating',
  'Crunching',
  'Crystallizing',
  'Cultivating',
  'Deciphering',
  'Deliberating',
  'Determining',
  'Dilly-dallying',
  'Discombobulating',
  'Doing',
  'Doodling',
  'Drizzling',
  'Ebbing',
  'Effecting',
  'Elucidating',
  'Embellishing',
  'Enchanting',
  'Envisioning',
  'Evaporating',
  'Fermenting',
  'Fiddle-faddling',
  'Finagling',
  'Flambéing',
  'Flibbertigibbeting',
  'Flowing',
  'Flummoxing',
  'Fluttering',
  'Forging',
  'Forming',
  'Frolicking',
  'Frosting',
  'Gallivanting',
  'Galloping',
  'Garnishing',
  'Generating',
  'Gesticulating',
  'Germinating',
  'Gitifying',
  'Grooving',
  'Gusting',
  'Harmonizing',
  'Hashing',
  'Hatching',
  'Herding',
  'Honking',
  'Hullaballooing',
  'Hyperspacing',
  'Ideating',
  'Imagining',
  'Improvising',
  'Incubating',
  'Inferring',
  'Infusing',
  'Ionizing',
  'Jitterbugging',
  'Julienning',
  'Kneading',
  'Leavening',
  'Levitating',
  'Lollygagging',
  'Manifesting',
  'Marinating',
  'Meandering',
  'Metamorphosing',
  'Misting',
  'Moonwalking',
  'Moseying',
  'Mulling',
  'Mustering',
  'Musing',
  'Nebulizing',
  'Nesting',
  'Newspapering',
  'Noodling',
  'Nucleating',
  'Orbiting',
  'Orchestrating',
  'Osmosing',
  'Perambulating',
  'Percolating',
  'Perusing',
  'Philosophising',
  'Photosynthesizing',
  'Pollinating',
  'Pondering',
  'Pontificating',
  'Pouncing',
  'Precipitating',
  'Prestidigitating',
  'Processing',
  'Proofing',
  'Propagating',
  'Puttering',
  'Puzzling',
  'Quantumizing',
  'Razzle-dazzling',
  'Razzmatazzing',
  'Recombobulating',
  'Reticulating',
  'Roosting',
  'Ruminating',
  'Sautéing',
  'Scampering',
  'Schlepping',
  'Scurrying',
  'Seasoning',
  'Shenaniganing',
  'Shimmying',
  'Simmering',
  'Skedaddling',
  'Sketching',
  'Slithering',
  'Smooshing',
  'Sock-hopping',
  'Spelunking',
  'Spinning',
  'Sprouting',
  'Stewing',
  'Sublimating',
  'Swirling',
  'Swooping',
  'Symbioting',
  'Synthesizing',
  'Tempering',
  'Thinking',
  'Thundering',
  'Tinkering',
  'Tomfoolering',
  'Topsy-turvying',
  'Transfiguring',
  'Transmuting',
  'Twisting',
  'Undulating',
  'Unfurling',
  'Unravelling',
  'Vibing',
  'Waddling',
  'Wandering',
  'Warping',
  'Whatchamacalliting',
  'Whirlpooling',
  'Whirring',
  'Whisking',
  'Wibbling',
  'Working',
  'Wrangling',
  'Zesting',
  'Zigzagging',
  'Locking in',
  'Cookin',
  'Cooking',
  'Speedrunning',
  'Vibe-coding',
  'Agenting',
  'Autopiloting',
  'Brainrotting',
  'Maxxing',
  'Aura-farming',
  'Flexing',
  'Grinding',
  'Mogging',
  'Syncing',
  'Prompting',
  'Chain-thinking',
  'Context-loading',
  'Tokenizing',
  'One-shotting',
  'Quickscoping',
  'Clutching',
  'Fragging',
  'Sweating',
  'No-lifing',
  'Meta-gaming',
  'Power-leveling',
  'Stacking',
  'Buffing',
  'Min-maxing',
  'Deploying',
  'Forking',
  'Committing',
  'Pushing',
  'Rebasing',
  'Refactoring',
  'Debugging',
  'Hotfixing',
  'Shipping',
  'Compiling',
  'Benchmarking',
  'Optimizing',
  'Caching',
  'Parallelizing',
  'Containerizing',
  'Orchestrating',
  'Container-pulling',
  'Self-hosting',
  'Homelabbing',
  'Inference-maxxing',
  'Agent-maxxing',
  'Reasoning',
  'Deep-thinking',
  'Ultra-thinking',
  'Hyper-focusing',
  'Context-maxxing',
  'Brainstorming',
  'Cooking up',
  'Scheming',
  'Plotting',
  'Summoning',
  'Grinding XP',
  'Farming XP',
  'Looting',
  'Crafting builds',
  'Touching grass',
  'Not touching grass',
  'Gigabraining',
  'Galaxy-braining',
  '4D-chessing',
  'Big-braining',
  'Locking tf in',
  'Cooking hard',
  'Going brrr',
  'Zooming',
  'Cranking',
  'Sending it',
  'Rawdogging',
  'Yeeting',
  'Rizzing',
  'Aura-maxxing',
  'Drip-checking',
  'Cookmaxxing',
  'Sweatmaxxing',
  'Grindseting',
  'Hustling',
  'Ghost-coding',
  'Cursoring',
  'Codexing',
  'Tovyr-coding',
  'Tovyring',
  'Prompt-engineering',
  'Agent-swarming',
  'Tool-calling',
  'Context-packing',
  'Model-routing',
  'Token-crunching',
  'GPU-melting',
  'VRAM-maxxing',
  'Benchmark-grinding',
  'Latency-hunting',
  'Throughput-maxxing',
  'Hallucinating',
  'Fact-checking',
  'Deep-diving',
  'Cooking tokens',
  'Spawning agents',
  'Vibe-checking',
  'Aura-checking',
  'Brain-buffering',
  'Neuron-firing',
  'Synapse-firing',
  'Quantum-cooking',
  'Hypercooking',
  'Overclocking',
  'Turbocharging',
  'Warp-speeding',
  'Reality-bending',
  'Dimension-hopping',
  'Multitasking',
  'Megathinking',
  'Ultra-instincting',
  'Side-questing',
  'Main-questing',
  'NPCing',
  'Boss-fighting',
  'Raid-leading',
  'Clan-stacking',
  'Leaderboard-climbing',
  'Rank-grinding',
  'Elo-farming',
  'W-keying',
  'Cracked-ing',
  'Diffing',
  'Skill-issuing',
  'Outplaying',
  'Carrying',
  'Hard-carrying',
  'Sweat-lording',
  'Tech-pilling',
  'Future-proofing',
  'Next-genning',
  'Brain-caching',
  'Data-mining',
  'Signal-boosting',
  'Internetting',
  'Cybering',
  'Cloud-hopping',
  'Agentifying',
  'AI-pilled-ing',
  'Automation-maxxing',
  'Workflow-maxxing',
  'Productivity-maxxing',
  'Knowledge-mining',
  'Pattern-matching',
  'Context-weaving',
  'Dreaming big',
  'Building cool stuff',
  'tungtungtungshaur',
]
