/**
 * Generate SDK type files from Zod schemas.
 * Run: bun scripts/generate-sdk-types.ts
 */
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import * as coreSchemas from '../src/entrypoints/sdk/coreSchemas.ts'
import * as controlSchemas from '../src/entrypoints/sdk/controlSchemas.ts'

const sdkDir = join(dirname(fileURLToPath(import.meta.url)), '../src/entrypoints/sdk')

function generateFromSchemas(
  schemas: Record<string, unknown>,
  outFile: string,
  importPath: string,
): number {
  const lines: string[] = [
    '// Auto-generated by scripts/generate-sdk-types.ts — do not edit',
    "import type { z } from 'zod/v4'",
    `import * as S from '${importPath}'`,
    '',
  ]

  let count = 0
  for (const [name, value] of Object.entries(schemas)) {
    if (!name.endsWith('Schema') || typeof value !== 'function') continue
    const typeName = name.slice(0, -'Schema'.length)
    lines.push(`export type ${typeName} = z.infer<ReturnType<typeof S.${name}>>`)
    count++
  }

  writeFileSync(join(sdkDir, outFile), `${lines.join('\n')}\n`)
  return count
}

const coreCount = generateFromSchemas(
  coreSchemas,
  'coreTypes.generated.ts',
  './coreSchemas.js',
)
const controlCount = generateFromSchemas(
  controlSchemas,
  'controlTypes.generated.ts',
  './controlSchemas.js',
)

console.log(`Wrote coreTypes.generated.ts (${coreCount} types)`)
console.log(`Wrote controlTypes.generated.ts (${controlCount} types)`)
